In [1]:
import pandas as pd

In [2]:
headers = [
    "alcohol",
    "malic_acid",
    "alcalinity_of_ash",
    "magnesium",
    "flavanoids",
    "proanthocyanins",
    "hue"
]
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')
df

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
173,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
174,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
175,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
176,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [3]:
#step 4
df = df.drop(columns = df.columns[[0,3,6,8,11,12,13]])
df.head()

   14.23  1.71  15.6  127  3.06  2.29  5.64
0  13.20  1.78  11.2  100  2.76  1.28  4.38
1  13.16  2.36  18.6  101  3.24  2.81  5.68
2  14.37  1.95  16.8  113  3.49  2.18  7.80
3  13.24  2.59  21.0  118  2.69  1.82  4.32
4  14.20  1.76  15.2  112  3.39  1.97  6.75

In [4]:
#step 5
df = df.set_axis(axis = 1, labels = headers)

In [5]:
#step 6
df.iloc[0:3] = pd.NA
df.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13.24,2.59,21.0,118.0,2.69,1.82,4.32
4,14.20,1.76,15.2,112.0,3.39,1.97,6.75

In [6]:
#step 7
df.loc[3:4,'magnesium'] = pd.NA

In [7]:
#step 8
df ['alcohol'] = df['alcohol'].fillna(10)
df ['magnesium'] = df['magnesium'].fillna(100)
df.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,NaN,NaN,100.0,NaN,NaN,NaN
1,10.00,NaN,NaN,100.0,NaN,NaN,NaN
2,10.00,NaN,NaN,100.0,NaN,NaN,NaN
3,13.24,2.59,21.0,100.0,2.69,1.82,4.32
4,14.20,1.76,15.2,100.0,3.39,1.97,6.75

In [8]:
#step 9
df.isna().sum().sum()

np.int64(15)

In [9]:
from random import randint

#step 10
arr10 = [randint(0,10) for _ in range(10)]
print(arr10)

[1, 7, 9, 8, 10, 7, 2, 7, 1, 6]

In [10]:
df.loc[arr10,:] = pd.NA

In [11]:
df.head(10)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,NaN,NaN,100.0,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13.24,2.59,21.0,100.0,2.69,1.82,4.32
4,14.20,1.76,15.2,100.0,3.39,1.97,6.75
5,14.39,1.87,14.6,96.0,2.52,1.98,5.25
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#step 12
df.isna().sum().sum()

np.int64(54)

In [14]:
#step 13
df = df.dropna(how = 'all')
df.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,NaN,NaN,100.0,NaN,NaN,NaN
3,13.24,2.59,21.0,100.0,2.69,1.82,4.32
4,14.20,1.76,15.2,100.0,3.39,1.97,6.75
5,14.39,1.87,14.6,96.0,2.52,1.98,5.25
11,13.75,1.73,16.0,89.0,2.76,1.81,5.60

In [24]:
df['alcohol'].loc[df['alcohol'].notna()]

0      10.00
3      13.24
4      14.20
5      14.39
11     13.75
       ...
172    13.71
173    13.40
174    13.27
175    13.17
176    14.13
Name: alcohol, Length: 170, dtype: float64

In [25]:
df = df.reset_index(drop = True)

In [26]:
df

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,NaN,NaN,100.0,NaN,NaN,NaN
1,13.24,2.59,21.0,100.0,2.69,1.82,4.32
2,14.20,1.76,15.2,100.0,3.39,1.97,6.75
3,14.39,1.87,14.6,96.0,2.52,1.98,5.25
4,13.75,1.73,16.0,89.0,2.76,1.81,5.60
...,...,...,...,...,...,...,...
165,13.71,5.65,20.5,95.0,0.61,1.06,7.70
166,13.40,3.91,23.0,102.0,0.75,1.41,7.30
167,13.27,4.28,20.0,120.0,0.69,1.35,10.20
168,13.17,2.59,20.0,120.0,0.68,1.46,9.30
169,14.13,4.10,24.5,96.0,0.76,1.35,9.20