## DAY 1

In [1]:
import pandas as pd

df = pd.read_table('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', index_col=0)

In [2]:
df.head(10)

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
3,1,Side of Chips,NaN,$1.69
4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [3]:
#observations
df['item_name'].count()

np.int64(4622)

In [4]:
#column names
df.columns.values

<StringArray>
['quantity', 'item_name', 'choice_description', 'item_price']
Length: 4, dtype: str

In [5]:
#col count
df.columns.size + 1

5

In [6]:
df = df.reset_index(drop=True)
df

,quantity,item_name,choice_description,item_price
0,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
2,1,Nantucket Nectar,[Apple],$3.39
3,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
4617,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [7]:
## most ordered item
df.item_name.value_counts().head(1).index[0]

'Chicken Bowl'

In [8]:
df.loc[(df.item_name == df.item_name.value_counts().head(1).index[0]), 'quantity'].sum()

np.int64(761)

In [9]:
df['choice_description'] = df['choice_description'].str.replace('[', '')
df['choice_description'] = df['choice_description'].str.replace(']', '')
df['choice_description'] = df['choice_description'].str.split(',').str[0]

In [10]:
#actual most sold choice description item
df.choice_description.value_counts().head(1)

choice_description
Fresh Tomato Salsa    1046
Name: count, dtype: int64

In [11]:
df

,quantity,item_name,choice_description,item_price
0,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,Clementine,$3.39
2,1,Nantucket Nectar,Apple,$3.39
3,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,Chicken Bowl,Tomatillo-Red Chili Salsa (Hot),$16.98
...,...,...,...,...
4617,1,Steak Burrito,Fresh Tomato Salsa,$11.75
4618,1,Steak Burrito,Fresh Tomato Salsa,$11.75
4619,1,Chicken Salad Bowl,Fresh Tomato Salsa,$11.25
4620,1,Chicken Salad Bowl,Fresh Tomato Salsa,$8.75
4621,1,Chicken Salad Bowl,Fresh Tomato Salsa,$8.75

In [12]:
df = pd.read_table('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', index_col=0)

In [13]:
#total ordered items
df.quantity.sum()

np.int64(4972)

In [14]:
df['item_price'] = df['item_price'].apply(lambda x: float(x.strip('$')))

In [15]:
df['item_price'].dtype

dtype('float64')

In [16]:
#total revenue
revenue = df['item_price'] * df['quantity']
revenue = revenue.sum()
revenue

np.float64(39237.02)

In [17]:
#how many orders
df.index.unique().size

1834

In [18]:
#avrg revenue per order
revenue = df['item_price'] * df['quantity']
revenue_per_order = revenue.groupby('order_id').sum()
revenue_per_order.mean()

np.float64(21.39423118865867)

In [19]:
#how many different items are sold
df['item_name'].value_counts().size

50

## DAY 2

In [28]:
df = pd.read_table('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv')

In [21]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [30]:
df.item_price =  df.item_price.apply(lambda x: float(x.replace('$','')))
df['single_item_price'] = df.item_price / df.quantity

In [25]:
df.loc[df['single_item_price'] > 10].drop_duplicates(subset=['item_name','choice_description'], keep='first')

,order_id,quantity,item_name,choice_description,item_price,single_item_price
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98,10.98
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75,11.75
...,...,...,...,...,...,...
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75,11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75,11.75
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75,11.75
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25,11.25

In [27]:
df.sort_values('item_name', ascending=False)

,order_id,quantity,item_name,choice_description,item_price,single_item_price
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98,8.49
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
...,...,...,...,...,...,...
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49,6.49
3789,1517,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1392,566,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
3614,1448,1,6 Pack Soft Drink,[Nestea],6.49,6.49

In [68]:
print(df.loc[(df.item_price == df.item_price.max()),'quantity'].iloc[0])

15

In [71]:
print(df.loc[(df.item_name == 'Veggie Salad Bowl'),'item_name'].count())

18

In [74]:
df.loc[((df.item_name.str.contains('Canned Soda'))&(df.quantity > 1)),['item_name','order_id']]

        item_name  order_id
18    Canned Soda         9
51    Canned Soda        23
162   Canned Soda        73
171   Canned Soda        76
350   Canned Soda       150
352   Canned Soda       151
698   Canned Soda       287
700   Canned Soda       288
909   Canned Soda       376
1091  Canned Soda       450
1092  Canned Soda       450
1944  Canned Soda       787
2135  Canned Soda       859
2235  Canned Soda       901
2905  Canned Soda      1156
2906  Canned Soda      1156
3152  Canned Soda      1258
3364  Canned Soda      1349
3592  Canned Soda      1440
3866  Canned Soda      1550