In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')

In [3]:
#4
df.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

In [4]:
#5
del df['Unnamed: 0']
del df['Id']

In [5]:
#6
df['Year'].value_counts().idxmax()
# df.groupby('Year').sum().idxmax()

np.int64(2008)

In [6]:
#7
print(df['Gender'].value_counts().idxmax())

F

In [7]:
names = df.groupby('Name').agg({'Count':'sum'})
names

         Count
Name
Aaban       12
Aadan       23
Aadarsh      5
Aaden     3426
Aadhav       6
...        ...
Zyra        42
Zyrah       11
Zyren        6
Zyria       59
Zyriah      58

[17632 rows x 1 columns]

In [8]:
len(df['Name'].unique())

17632

In [9]:
df.groupby('Name')['Count'].sum().idxmax()

'Jacob'

In [10]:
min_occ = df.groupby('Name')['Count'].sum().min()
len(names[names['Count'] == min_occ])

2578

In [14]:
df.groupby('Name').agg({'Count':'sum'}).median().max()

np.float64(49.0)

In [12]:
names.Count.std()

np.float64(11006.06946789057)

In [13]:
names.describe()

               Count
count   17632.000000
mean     2008.932169
std     11006.069468
min         5.000000
25%        11.000000
50%        49.000000
75%       337.000000
max    242874.000000