In [20]:
import pandas as pd
from jupyter_core.migrate import regex
from numpy.ma.core import std

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data', delimiter=r'\s+')

In [22]:
df

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,78,12,27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,78,12,28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,78,12,29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,78,12,30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,78,12,31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [23]:
#step 4
df['Yr'] = df['Yr']+1900

In [40]:
#step 3
df['Yr'] = df['Yr'].astype(str)
df['Mo'] = df['Mo'].astype(str)
df['Dy'] = df['Dy'].astype(str)
df['Yr'] = df['Yr'] + '-' + df['Mo'] + '-' + df['Dy']
del df['Date']
del df['Mo']
del df['Dy']
df.rename({'Yr':'Date'}, axis=1, inplace=True)

In [53]:
#step 4
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')

In [56]:
#step 5
df = df.set_index('Date')

In [69]:
df

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [68]:
#step 6
df.isna().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

In [70]:
#step 7
df.isna().sum().sum()

np.int64(31)

In [200]:
#step 8
df.mean().mean()

np.float64(10.227982360836938)

In [97]:
#step 9
df.agg(['min', 'max', 'mean', 'std'])

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794

In [119]:
#step 10
df.agg(['min', 'max', 'mean', 'std'], axis=1)

             min    max       mean       std
Date
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

In [175]:
#step 11
only_jan = df.loc[df.index.month == 1]
only_jan.mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

In [179]:
#step 12
df.groupby(df.index.year).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

In [186]:
#step 13
df.groupby(df.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

In [188]:
#step 14
df.groupby(df.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1960-12-26/1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-02/1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-16/1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-23/1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

In [199]:
#step 15
filtered = df.loc[df.index > pd.to_datetime('1961-01-01')]
filtered.groupby(filtered.index.to_period('W')).agg(['min','max','mean','std']).stack().head(52)

                                  RPT        VAL        ROS        KIL  \
Date
1961-01-02/1961-01-08 min   10.580000   6.630000   7.620000   4.580000
                      max   18.500000  16.880000  12.330000  10.130000
                      mean  13.541429  11.486667  10.487143   6.417143
                      std    2.631321   3.949525   1.604761   1.810743
1961-01-09/1961-01-15 min    9.040000   3.540000   7.080000   0.670000
                      max   19.750000  12.080000  19.500000  10.540000
                      mean  12.468571   8.967143  11.958571   4.630000
                      std    3.555392   3.148945   5.034959   3.549559
1961-01-16/1961-01-22 min    4.920000   3.420000   7.290000   1.040000
                      max   19.830000  14.370000  20.790000  18.540000
                      mean  13.204286   9.862857  12.982857   6.328571
                      std    5.337402   3.837785   5.086229   6.245541
1961-01-23/1961-01-29 min   13.620000   9.960000  12.670000   6.040000
                      max   25.040000  23.910000  25.840000  17.540000
                      mean  19.880000  16.141429  18.225714  12.720000
                      std    4.619061   5.170224   4.665843   4.301325
1961-01-30/1961-02-05 min   10.580000   9.460000   9.040000   5.090000
                      max   24.210000  24.210000  19.700000  11.960000
                      mean  16.827143  15.460000  12.618571   8.247143
                      std    5.251408   5.187395   3.975166   2.709106
1961-02-06/1961-02-12 min   16.000000  11.540000  13.670000   8.380000
                      max   24.540000  21.420000  21.340000  15.370000
                      mean  19.684286  16.417143  17.304286  10.774286
                      std    3.587677   3.608373   3.290303   2.262056
1961-02-13/1961-02-19 min    6.040000  11.630000   6.130000   4.210000
                      max   22.500000  20.170000  19.410000  15.340000
                      mean  15.130000  15.091429  13.797143  10.083333
                      std    5.064609   3.575012   4.196621   4.311569
1961-02-20/1961-02-26 min    7.790000   7.080000   6.080000   2.210000
                      max   25.800000  21.500000  22.420000  15.210000
                      mean  15.221429  13.625714  14.334286   8.524286
                      std    7.020716   5.147348   5.578470   4.482075
1961-02-27/1961-03-05 min   10.960000   8.830000   8.170000   5.880000
                      max   13.330000  17.000000  13.670000  10.040000
                      mean  12.101429  12.951429  11.063333   7.834286
                      std    0.997721   2.851955   1.796871   1.652572
1961-03-06/1961-03-12 min    4.880000   8.080000   7.540000   3.130000
                      max   14.790000  16.960000  16.380000  10.250000
                      mean   9.376667  11.578571  10.845714   7.137143
                      std    3.732263   3.230167   3.592909   2.609928
1961-03-13/1961-03-19 min    4.920000   9.460000   5.250000   4.290000
                      max   16.880000  15.540000  13.960000  11.040000
                      mean  11.911429  13.501429  11.607143   7.084286
                      std    3.860036   2.352867   2.939244   2.416746
1961-03-20/1961-03-26 min    6.290000   2.580000   4.790000   4.420000
                      max   15.000000  11.630000  15.630000  10.750000
                      mean   9.567143   8.387143   9.695714   6.648571
                      std    3.613298   3.657265   4.041121   2.410127
1961-03-27/1961-04-02 min    5.880000   3.500000   5.090000   2.750000
                      max   18.250000  16.290000  14.960000  12.000000
                      mean  10.757143   8.852857   9.501429   7.300000
                      std    5.046922   4.687315   3.678996   3.625488

                                  SHA        BIR        DUB        CLA  \
Date
1961-01-02/1961-01-08 min    4.540000   2.880000   8.630000   1.790000
                      max   12.620000   8.330000  14.290000  10.040000
                      mean   9.474286   6.435714  11.061429   6.616667
                      std    3.251660   2.059546   1.872222   3.098404
1961-01-09/1961-01-15 min    2.290000   0.960000   2.500000   0.580000
                      max   10.370000   9.460000  15.540000  11.500000
                      mean   7.351429   5.072857   7.535714   6.820000
                      std    3.471726   3.251039   4.709309   3.936894
1961-01-16/1961-01-22 min    3.670000   3.170000   3.170000   2.790000
                      max   13.960000  13.370000  17.830000  11.380000
                      mean   8.966667   7.417143   9.257143   7.875714
                      std    3.612875   3.453432   5.166300   3.164990
1961-01-23/1961-01-29 min   10.000000   9.420000   9.250000   8.710000
                      max   24.080000  19.700000  22.000000  20.250000
                      mean  17.432857  14.828571  15.528571  15.160000
                      std    4.858116   3.749415   4.508449   4.436222
1961-01-30/1961-02-05 min    9.870000   5.830000   8.500000   3.630000
                      max   17.370000  12.040000  14.880000  15.540000
                      mean  13.361429   9.107143  12.204286   8.548571
                      std    2.334619   2.397066   2.423454   4.081158
1961-02-06/1961-02-12 min    8.120000   8.080000  11.080000   9.710000
                      max   25.330000  17.620000  19.170000  18.790000
                      mean  14.718571  12.522857  14.934286  14.850000
                      std    5.571108   3.048976   2.974059   3.022753
1961-02-13/1961-02-19 min    9.870000   6.920000   3.420000   7.410000
                      max   16.130000  15.120000  16.080000  14.290000
                      mean  13.410000  11.868571   9.542857  12.128571
                      std    2.321716   3.024078   4.958631   2.283444
1961-02-20/1961-02-26 min    5.960000   4.330000   3.750000   4.670000
                      max   23.090000  16.880000  21.170000  17.250000
                      mean  13.655714  10.114286  11.150000  10.875714
                      std    6.480712   5.029874   6.037916   4.869668
1961-02-27/1961-03-05 min    8.250000   6.000000   5.500000   5.660000
                      max   16.130000  12.290000  14.750000  14.460000
                      mean  12.101429   9.238571  10.232857  11.130000
                      std    2.957129   2.022247   3.338177   2.877395
1961-03-06/1961-03-12 min    5.410000   4.080000   1.710000   5.290000
                      max   14.920000  13.670000  17.120000  15.670000
                      mean  10.940000   9.488571   6.881429   9.637143
                      std    3.110857   3.440419   5.537269   3.760557
1961-03-13/1961-03-19 min    6.830000   5.790000   2.750000   5.130000
                      max   14.370000  10.750000  13.960000  14.290000
                      mean  10.751429   8.652857  10.041429  10.220000
                      std    2.654289   2.045448   4.046593   3.373421
1961-03-20/1961-03-26 min    5.130000   4.290000   8.000000   4.920000
                      max   13.330000  10.290000  15.410000  13.040000
                      mean   8.964286   7.982857  10.774286   8.977143
                      std    2.927188   2.285729   2.892270   2.789682
1961-03-27/1961-04-02 min    2.830000   3.500000   5.250000   1.460000
                      max   18.340000  14.330000  16.620000  14.920000
                      mean   9.975714   9.165714  11.125714   9.061429
                      std    5.657679   4.054639   4.047068   4.689504

                                  MUL        CLO        BEL        MAL
Date
1961-01-02/1961-01-08 min    5.830000   5.880000   5.460000  10.880000
                      max   10.920000  10.460000  17.540000  16.460000
                      mean   8.434286   8.497143  12.481429  13.238571
                      std    1.722255   1.704941   4.349139   1.773062
1961-01-09/1961-01-15 min    0.500000   2.670000   5.250000   5.170000
                      max   10.370000  14.580000  20.710000  16.920000
                      mean   5.712857   7.571429  11.125714  11.024286
                      std    3.500975   4.084293   5.552215   4.692355
1961-01-16/1961-01-22 min    1.920000   2.710000   6.500000   6.790000
                      max   14.670000  16.710000  15.920000  17.960000
                      mean   7.145714   8.124286   9.821429  11.434286
                      std    4.169112   4.783952   3.626584   4.237239
1961-01-23/1961-01-29 min    7.120000  11.040000  14.040000  17.500000
                      max   21.460000  19.950000  27.710000  27.630000
                      mean  14.480000  15.640000  20.930000  22.530000
                      std    4.902057   3.713368   5.210726   3.874721
1961-01-30/1961-02-05 min    6.340000   5.500000   9.170000   7.170000
                      max   13.370000  13.130000  19.330000  19.250000
                      mean   9.821429   9.460000  14.012857  11.935714
                      std    2.802490   2.839501   4.210858   4.336104
1961-02-06/1961-02-12 min   10.370000  12.250000  15.210000  17.040000
                      max   18.960000  17.790000  26.380000  21.840000
                      mean  14.064286  14.440000  21.832857  19.155714
                      std    2.914760   1.746749   4.063753   1.828705
1961-02-13/1961-02-19 min    8.170000   9.210000  14.090000  10.960000
                      max   14.880000  16.580000  29.630000  22.580000
                      mean  12.375714  13.542857  21.167143  16.584286
                      std    2.560591   2.531361   5.910938   4.685377
1961-02-20/1961-02-26 min    4.500000   7.000000   9.590000   6.670000
                      max   18.460000  20.040000  23.210000  23.870000
                      mean  10.392857  12.730000  16.304286  14.322857
                      std    4.705163   4.920064   5.091162   6.182283
1961-02-27/1961-03-05 min    6.250000   9.790000  11.580000   8.830000
                      max   13.960000  14.090000  23.450000  17.540000
                      mean  10.383333  12.370000  17.842857  13.951667
                      std    2.610124   1.593685   4.332331   3.021387
1961-03-06/1961-03-12 min    5.210000   5.090000  10.210000   5.540000
                      max   16.290000  15.790000  22.710000  22.540000
                      mean   9.885714  10.458571  16.701429  14.420000
                      std    3.657690   3.655113   4.358759   5.769890
1961-03-13/1961-03-19 min    6.000000   7.290000  11.290000  11.340000
                      max   13.880000  15.340000  22.790000  22.950000
                      mean  10.101429  11.627143  19.350000  16.227143
                      std    3.301880   3.099472   3.779727   4.331958
1961-03-20/1961-03-26 min    8.000000   8.330000   8.250000  13.130000
                      max   14.370000  14.500000  21.340000  22.500000
                      mean  10.904286  11.481429  14.037143  18.134286
                      std    2.469432   2.538224   4.318069   3.701846
1961-03-27/1961-04-02 min    6.500000   6.460000   7.210000   7.170000
                      max   17.540000  14.210000  18.630000  19.580000
                      mean  10.478333   9.631429  13.471429  13.900000
                      std    4.025317   3.191115   4.179854   3.924555